### GET

GET http://localhost:3001/api/blogs

### POST
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test blog entry",
  "author": "Tester Dude",
  "url": "http://www.example.com",
  "likes": 5
}

### DELETE
DELETE http://localhost:3001/api/blogs/698989944dbb62893cf3f7a2
