### GET BLGOS
GET http://localhost:3001/api/blogs

### GET USERS
GET http://localhost:3001/api/users

### POST BLOG
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7
}

### POST/CREATE USER
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Super User",
  "password": "salainen"
}

### DELETE BLOG
DELETE http://localhost:3001/api/blogs/698989944dbb62893cf3f7a2

### PUT/UPDATE BLOG
PUT http://localhost:3001/api/blogs/699580697cee531696a0eb3c
