### GET BLGOS
GET http://localhost:3001/api/blogs

### GET USERS
GET http://localhost:3001/api/users

### POST BLOG
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test blog entry",
  "author": "Tester Dude",
  "url": "http://www.example.com",
  "likes": 5
}

### DELETE BLGO
DELETE http://localhost:3001/api/blogs/698989944dbb62893cf3f7a2

### PUT/UPDATE BLOG
PUT http://localhost:3001/api/blogs/699580697cee531696a0eb3c
